# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rt60Page.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Rt60Page(object):
    def setupUi(self, Rt60Page):
        Rt60Page.setObjectName("Rt60Page")
        Rt60Page.resize(610, 904)
        self.rt60_graphicsView = QtWidgets.QGraphicsView(Rt60Page)
        self.rt60_graphicsView.setGeometry(QtCore.QRect(70, 510, 471, 321))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.rt60_graphicsView.setFont(font)
        self.rt60_graphicsView.setObjectName("rt60_graphicsView")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Rt60Page)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(66, 30, 481, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.verticalLayoutWidget_2.setFont(font)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setLineWidth(1)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.length = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.length.setFont(font)
        self.length.setObjectName("length")
        self.horizontalLayout.addWidget(self.length)
        self.room_length = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.room_length.setFont(font)
        self.room_length.setObjectName("room_length")
        self.horizontalLayout.addWidget(self.room_length)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.width = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.width.setFont(font)
        self.width.setObjectName("width")
        self.horizontalLayout.addWidget(self.width)
        self.room_width = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.room_width.setFont(font)
        self.room_width.setObjectName("room_width")
        self.horizontalLayout.addWidget(self.room_width)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.height = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.height.setFont(font)
        self.height.setObjectName("height")
        self.horizontalLayout.addWidget(self.height)
        self.room_height = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.room_height.setFont(font)
        self.room_height.setObjectName("room_height")
        self.horizontalLayout.addWidget(self.room_height)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.displaRoomModel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.displaRoomModel.setFont(font)
        self.displaRoomModel.setObjectName("displaRoomModel")
        self.verticalLayout_2.addWidget(self.displaRoomModel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.material_selection = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.material_selection.setFont(font)
        self.material_selection.setObjectName("material_selection")
        self.material_selection.addItem("")
        self.material_selection.addItem("")
        self.material_selection.addItem("")
        self.material_selection.addItem("")
        self.horizontalLayout_4.addWidget(self.material_selection)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 4, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout.addWidget(self.comboBox_6, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.calculateRT60 = QtWidgets.QPushButton(Rt60Page)
        self.calculateRT60.setGeometry(QtCore.QRect(250, 480, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.calculateRT60.setFont(font)
        self.calculateRT60.setObjectName("calculateRT60")

        self.retranslateUi(Rt60Page)
        QtCore.QMetaObject.connectSlotsByName(Rt60Page)

    def retranslateUi(self, Rt60Page):
        _translate = QtCore.QCoreApplication.translate
        Rt60Page.setWindowTitle(_translate("Rt60Page", "Form"))
        self.label_4.setText(_translate("Rt60Page", "RT60 Calculator "))
        self.length.setText(_translate("Rt60Page", "Length:"))
        self.label_8.setText(_translate("Rt60Page", "m "))
        self.width.setText(_translate("Rt60Page", "Width:"))
        self.label_9.setText(_translate("Rt60Page", "m "))
        self.height.setText(_translate("Rt60Page", "Height:"))
        self.label_10.setText(_translate("Rt60Page", "m "))
        self.displaRoomModel.setText(_translate("Rt60Page", "Display room model"))
        self.label_5.setText(_translate("Rt60Page", "Selection of wall material:"))
        self.material_selection.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.material_selection.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.material_selection.setItemText(2, _translate("Rt60Page", "Brick"))
        self.material_selection.setItemText(3, _translate("Rt60Page", "Wood"))
        self.comboBox_4.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox_4.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox_4.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox_4.setItemText(3, _translate("Rt60Page", "Wood"))
        self.label_2.setText(_translate("Rt60Page", "Back"))
        self.comboBox.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox.setItemText(3, _translate("Rt60Page", "Wood"))
        self.comboBox_5.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox_5.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox_5.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox_5.setItemText(3, _translate("Rt60Page", "Wood"))
        self.comboBox_2.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox_2.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox_2.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox_2.setItemText(3, _translate("Rt60Page", "Wood"))
        self.comboBox_3.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox_3.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox_3.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox_3.setItemText(3, _translate("Rt60Page", "Wood"))
        self.label.setText(_translate("Rt60Page", "Front"))
        self.comboBox_6.setItemText(0, _translate("Rt60Page", "Marble or Tile"))
        self.comboBox_6.setItemText(1, _translate("Rt60Page", "Concrete"))
        self.comboBox_6.setItemText(2, _translate("Rt60Page", "Brick"))
        self.comboBox_6.setItemText(3, _translate("Rt60Page", "Wood"))
        self.label_3.setText(_translate("Rt60Page", "Left"))
        self.label_11.setText(_translate("Rt60Page", "Right"))
        self.label_12.setText(_translate("Rt60Page", "Ceiling"))
        self.label_13.setText(_translate("Rt60Page", "Floor"))
        self.calculateRT60.setText(_translate("Rt60Page", "CALCULATE"))

