# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SplPage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SplPage(object):
    def setupUi(self, SplPage):
        SplPage.setObjectName("SplPage")
        SplPage.resize(626, 961)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(SplPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 451, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.horizontalLayoutWidget_2.setFont(font)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spl_result_text = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spl_result_text.setFont(font)
        self.spl_result_text.setObjectName("spl_result_text")
        self.horizontalLayout_2.addWidget(self.spl_result_text)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gridLayoutWidget = QtWidgets.QWidget(SplPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 70, 545, 341))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.No_of_Speakers = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.No_of_Speakers.setFont(font)
        self.No_of_Speakers.setObjectName("No_of_Speakers")
        self.gridLayout_2.addWidget(self.No_of_Speakers, 4, 1, 1, 1)
        self.length_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length_3.setFont(font)
        self.length_3.setObjectName("length_3")
        self.gridLayout_2.addWidget(self.length_3, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 3, 2, 1, 1)
        self.length_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length_6.setFont(font)
        self.length_6.setObjectName("length_6")
        self.gridLayout_2.addWidget(self.length_6, 3, 0, 1, 1)
        self.SpeakerSensitivity = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.SpeakerSensitivity.setFont(font)
        self.SpeakerSensitivity.setObjectName("SpeakerSensitivity")
        self.gridLayout_2.addWidget(self.SpeakerSensitivity, 0, 1, 1, 1)
        self.AmplifierPower = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.AmplifierPower.setFont(font)
        self.AmplifierPower.setObjectName("AmplifierPower")
        self.gridLayout_2.addWidget(self.AmplifierPower, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_1.setFont(font)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout_2.addWidget(self.radioButton_1, 8, 1, 1, 1)
        self.length_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length_8.setFont(font)
        self.length_8.setObjectName("length_8")
        self.gridLayout_2.addWidget(self.length_8, 4, 0, 1, 1)
        self.length_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length_7.setFont(font)
        self.length_7.setObjectName("length_7")
        self.gridLayout_2.addWidget(self.length_7, 8, 0, 1, 1)
        self.Distance = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Distance.setFont(font)
        self.Distance.setObjectName("Distance")
        self.gridLayout_2.addWidget(self.Distance, 3, 1, 1, 1)
        self.length_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.length_4.setFont(font)
        self.length_4.setObjectName("length_4")
        self.gridLayout_2.addWidget(self.length_4, 2, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_2.addWidget(self.radioButton_2, 9, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_2.addWidget(self.radioButton_3, 10, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 2, 1, 1)
        self.calculateSPL = QtWidgets.QPushButton(SplPage)
        self.calculateSPL.setGeometry(QtCore.QRect(230, 410, 141, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.calculateSPL.setFont(font)
        self.calculateSPL.setObjectName("calculateSPL")
        self.tabWidget = QtWidgets.QTabWidget(SplPage)
        self.tabWidget.setGeometry(QtCore.QRect(10, 500, 581, 461))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2d = QtWidgets.QWidget()
        self.tab_2d.setObjectName("tab_2d")
        self.spl_graphicsView_2d = QtWidgets.QGraphicsView(self.tab_2d)
        self.spl_graphicsView_2d.setGeometry(QtCore.QRect(0, 0, 571, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spl_graphicsView_2d.setFont(font)
        self.spl_graphicsView_2d.setObjectName("spl_graphicsView_2d")
        self.tabWidget.addTab(self.tab_2d, "")
        self.tab_3d = QtWidgets.QWidget()
        self.tab_3d.setObjectName("tab_3d")
        self.spl_graphicsView_3d = QtWidgets.QGraphicsView(self.tab_3d)
        self.spl_graphicsView_3d.setGeometry(QtCore.QRect(0, 0, 571, 441))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.spl_graphicsView_3d.setFont(font)
        self.spl_graphicsView_3d.setObjectName("spl_graphicsView_3d")
        self.tabWidget.addTab(self.tab_3d, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(SplPage)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 30, 131, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(SplPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SplPage)

    def retranslateUi(self, SplPage):
        _translate = QtCore.QCoreApplication.translate
        SplPage.setWindowTitle(_translate("SplPage", "Form"))
        self.label_7.setText(_translate("SplPage", "Result:"))
        self.label_6.setText(_translate("SplPage", "dB SPL at listening Position"))
        self.length_3.setText(_translate("SplPage", "Speaker Sensitivity:"))
        self.label_18.setText(_translate("SplPage", "m"))
        self.length_6.setText(_translate("SplPage", "Distance:"))
        self.label_15.setText(_translate("SplPage", "dB SPL(1W/1M)"))
        self.radioButton_1.setText(_translate("SplPage", "Away from walls(or do not consider placement)"))
        self.length_8.setText(_translate("SplPage", "No.of Speakers:"))
        self.length_7.setText(_translate("SplPage", "Speaker Placement:"))
        self.length_4.setText(_translate("SplPage", "Amplifier Power:"))
        self.radioButton_2.setText(_translate("SplPage", "Near a wall (within 2 to 4 feet)"))
        self.radioButton_3.setText(_translate("SplPage", "In a corner (within 18 to 24 inches)"))
        self.label_19.setText(_translate("SplPage", "usually 2"))
        self.label_16.setText(_translate("SplPage", "Watts"))
        self.calculateSPL.setText(_translate("SplPage", "CALCULATE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2d), _translate("SplPage", "2D"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3d), _translate("SplPage", "3D"))
        self.label.setText(_translate("SplPage", "SPL Calculator "))

